# name of the software
name: Digipost API client for .NET
# current version of the software
version: 1.0
# url of the download button
downloadUrl: https://www.nuget.org/packages/digipost-api-client/
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

#baseurl: "/sikker-digital-post-net-klient" # the subpath of your site, e.g. /blog/
coreUrl: "/digipost-api-client-dotnet"
collections:
  doks:
    output: true

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-dotnet

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-dotnet
  - title: Issues
    url: https://github.com/digipost/digipost-api-client-dotnet/issues

# header
header:
  color1: "#606369"
  color2: "#4D4F53"
  trianglify: true

# github buttons
githubButton:
  user: digipost
  repo: digipost-api-client-dotnet

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  account:
  domain:

# DON'T MODIFY
highlight: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
