# name of the software
title: Digipost API client library for Java
# current version of the software
version: 1.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

#baseurl: "/sikker-digital-post-net-klient" # the subpath of your site, e.g. /blog/
baseurl: "/digipost-api-client-java"

currentVersion: "10.x"
versions: ["10.x", "9.0", "8.0", "6.1", "6.0"]

collections:
  v6_0:  
    output: true
    permalink: /v6.0/    
  v6_1:
    output: true
    permalink: /v6.1/
  v8_0:
    output: true
    permalink: /v8.0/
  v9_0:
    output: true
    permalink: /v9.0/
  v10_x:
    output: true
    permalink: /v10.x/

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://github.com/digipost/digipost-api-client-java
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-java
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-java
  - title: Issues
    url: https://github.com/digipost/digipost-api-client-java/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: digipost-api-client-java

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  account:
  domain:

# DON'T MODIFY
highlight: rouge

github: [metadata]

plugins:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
